### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED while attempting P1 npx idk deploy

### ISSUE THREAD

**Issue by BenWilkens** [davidtucker/ps-serverless-app#10]
I have been following this course with no issue using PyCharm pro as my IDE, so do not believe that is the issue but have just run into an error that does not appear to have a clear resolution. 

I was able to successfully deploy the application earlier in the P1 course section prior to adding this section in webapp.ts:

// Deploy Web App ---------------------------------------------------------

        new cwt.WebAppDeployment(this, 'WebAppDeploy', {
            baseDirectory: props.baseDirectory,
            relativeWebAppPath: props.relativeWebAppPath,
            webDistribution: this.webDistribution,
            webDistributionPaths: ['/*'],
            buildCommand: 'yarn build',
            buildDirectory: 'build',
            bucket: props.hostingBucket,
            prune:true
        });

        new cdk.CfnOutput(this, 'URL', {
            value: `https://${this.webDistribution.distributionDomainName}/`
        });`

After adding this (and the related entries in index.ts): 
` baseDirectory: '../',
      relativeWebAppPath: 'webapp',
    });`

I am now receiving the following error when attempting to run npx cdk deploy:

`[my user]@MacBook-Pro: ~/PycharmProjects/ps-serverless-app/infrastructure p1!
$ npx cdk deploy                                                                                                                                                                               [12:19:19]
Bundling asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage...
yarn run v1.22.15
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-501".
$ react-scripts build
warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/asset-input/node_modules/webpack/lib/NormalModule.js:471:10)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:503:5
    at /asset-input/node_modules/webpack/lib/NormalModule.js:358:12
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/asset-input/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:452:10
    at /asset-input/node_modules/webpack/lib/NormalModule.js:323:13
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /asset-input/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Failed to bundle asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage, bundle output is located at /Users/[my user]/PycharmProjects/ps-serverless-app/infrastructure/cdk.out/asset.8c7ae86f7dabf723a79310f22f328c471bdaec37da5325cd834784dc03a40eff-error: Error: docker exited with status 1
Subprocess exited with error 1
FAIL`

 It appears that this might be a Yarn issue, but following [these](https://stackoverflow.com/questions/69665222/node-17-0-1-causes-some-error-digital-envelope-routinesunsupported) instructions and adding 
 `    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",`  

to my package.json file does not resolve or change the output in any way.

Any input would be most appreciated!  I'm hoping I've missed something obvious here.

**Comment by BenWilkens** [comment]
I was able to resolve this issue.

The error appears to be related to the attempted use of the deprecated MD4 hash after updating npm to v8.1.3

There is some helpful information [here](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported).  The answer posted by Cheshiremoe indicates that this code should be added to node_modules\react-scripts\config\webpack.config.js

`const crypto = require("crypto");
const crypto_orig_createHash = crypto.createHash;
crypto.createHash = algorithm => crypto_orig_createHash(algorithm == "md4" ? "sha256" : algorithm);`

Once I added this code, `npx cdk deploy` no longer returns this error.

yarn v1.22.17
node v16.13.0 (lts)
npm v8.1.3
cdk v1.130.0
