### ISSUE TITLE
Error on npx cdk deploy

### ISSUE THREAD

**Issue by kasunsjc** [davidtucker/ps-serverless-app#11]
Following error thrown. Running the command after checkout to p2 branch 

npx cdk deploy                     
Bundling asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage...
yarn run v1.22.15
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-501".
$ react-scripts build
warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/asset-input/node_modules/webpack/lib/NormalModule.js:471:10)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:503:5
    at /asset-input/node_modules/webpack/lib/NormalModule.js:358:12
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/asset-input/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:452:10
    at /asset-input/node_modules/webpack/lib/NormalModule.js:323:13
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /asset-input/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/asset-staging.ts:472
  for (const key of Object.keys(object).sort()) {
            ^
Error: Failed to bundle asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage, bundle output is located at /Users/kasunrajapakse/Desktop/ps-serverless-app/infrastructure/cdk.out/asset.57fe83670650746cd594a8c1c7be0ff34d1f750120c2e51d7b80021d08f81928-error: Error: docker exited with status 1
    at AssetStaging.bundle (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/asset-staging.ts:472:13)
    at AssetStaging.stageByBundling (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/asset-staging.ts:330:10)
    at stageThisAsset (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/asset-staging.ts:196:35)
    at Cache.obtain (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13)
    at new AssetStaging (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/core/lib/asset-staging.ts:221:44)
    at new Asset (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:127:21)
    at Object.bind (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/aws-s3-deployment/lib/source.ts:89:23)
    at /Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:213:83
    at Array.map (<anonymous>)
    at new BucketDeployment (/Users/kasunrajapakse/Desktop/ps-serverless-app/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:213:51)
Subprocess exited with error 1

**Comment by malibeg** [comment]
Same here error here. I'm on Mac and it's not trying to build against local dir but on docker with docker image (node 17 ) as stated in https://github.com/davidtucker/cdk-webapp-tools/blob/main/API.md#class-webappdeployment--

**Comment by malibeg** [comment]
You can pass docker image param to use different version of node.js. I use node 12 image like below
```   
 new cwt.WebAppDeployment(this, 'WebAppDeploy', {
      baseDirectory: props.baseDirectory,
      relativeWebAppPath: props.relativeWebAppPath,
      webDistribution: this.webDistribution,
      webDistributionPaths: ['/*'],
      dockerImage: cdk.DockerImage.fromRegistry('node:12-alpine3.12'),
      buildCommand: 'yarn build',
      buildDirectory: 'build',
      bucket: props.hostingBucket,
      prune: false
    });
````

**Comment by kasunsjc** [comment]
@malibeg Thanks that works for me (Y)
