### ISSUE TITLE
Webpack error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by aRaghed** [davidtucker/ps-serverless-app#12]
Seems that the webpack is not compatible with the node version running in the docker image. I'm quite new to nodejs and can't figure out the problem by myself since i've never used webpack before. could you please assist me?
Webpack just released a new version of webpack https://github.com/webpack/webpack/releases/tag/v5.61.0 that should be compatible but i can't figure out how webpack gets introduced in the project.

rn run v1.22.17
$ react-scripts build
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/asset-input/node_modules/webpack/lib/NormalModule.js:471:10)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:503:5
    at /asset-input/node_modules/webpack/lib/NormalModule.js:358:12
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /asset-input/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/asset-input/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/asset-input/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/asset-input/node_modules/webpack/lib/NormalModule.js:417:16)
    at /asset-input/node_modules/webpack/lib/NormalModule.js:452:10
    at /asset-input/node_modules/webpack/lib/NormalModule.js:323:13
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /asset-input/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/asset-input/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /asset-input/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\asset-staging.ts:472
  for (const key of Object.keys(object).sort()) {
            ^
Error: Failed to bundle asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage, bundle output is located at C:\git-repos\React\ps-serverless-app\infrastructure\cdk.out\asset.a2537f899bb0358007d10021fdccddce4faf6344e6dc86c9a335d8a31bf2f575-error: Error: docker exited with status 1
    at AssetStaging.bundle (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\asset-staging.ts:472:13)
    at AssetStaging.stageByBundling (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\asset-staging.ts:330:10)
    at stageThisAsset (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\asset-staging.ts:196:35)
    at Cache.obtain (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\private\cache.ts:24:13)
    at new AssetStaging (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\core\lib\asset-staging.ts:221:44)
    at new Asset (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\aws-s3-assets\lib\asset.ts:127:21)
    at Object.bind (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\aws-s3-deployment\lib\source.ts:89:23)
    at C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\aws-s3-deployment\lib\bucket-deployment.ts:213:83
    at Array.map (<anonymous>)
    at new BucketDeployment (C:\git-repos\React\ps-serverless-app\node_modules\@aws-cdk\aws-s3-deployment\lib\bucket-deployment.ts:213:51)
Subprocess exited with error 1

C:\git-repos\React\ps-serverless-app\infrastructure>node version
node version
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'C:\git-repos\React\ps-serverless-app\infrastructure\version'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

PS:
There is a unsafe workaround, but as mentioned it's unsafe.
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by meibutuoyaji** [comment]
i had the exactly same issues with the same version of node

**Comment by TheLeePriest** [comment]
I had this exact same issue. Try setting the build command to this in the package.json file:

`    "build": "react-scripts --openssl-legacy-provider build",`

**Comment by bjwealthy** [comment]
I'm having this error!

**Comment by onedumbtrucker** [comment]
Same here. none of the suggested solutions on the web seem to work.

**Comment by davidtucker** [comment]
Apologies for the delay.  I'll work to research and provide an update very soon on this issue.

**Comment by onedumbtrucker** [comment]
Appreciate that thank you. The web consensus seems to be that it's an issue with Node 17. Unfortunately using nvm to downgrade Node to 16.3 or another LTS supported by the CDK does not appear to actually change the version used by the CDK as it shows Node 18.0.0 during the deployment even though nvm list currently shows 16.3.0

**Comment by onedumbtrucker** [comment]
Hi David,
That did fix the main issue and it seems to build most of the application but it fails during pipeline creation now
![image](https://user-images.githubusercontent.com/23708543/165971658-91fd4968-c600-43ff-a30a-021a18fe5b36.png)
