### ISSUE TITLE
WebApp Deployment Failed

### ISSUE THREAD

**Issue by kali70** [davidtucker/ps-serverless-app#28]
Hello David and thank you very much for this amazing CDK path. 

I am following your videos using this git repo but I am having an issue deploying to CloudFront in the P1 branch using cdkv2.

I posted the error below which I got after I run `npx cdk deploy`

 
**Error: Bundling did not produce any output. Check that content is written to /asset-output.
    at AssetStaging.bundle (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:841)
    at AssetStaging.stageByBundling (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:4506)
    at stageThisAsset (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:1867)
    at Cache.obtain (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2262)
    at new Asset (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
    at Object.bind (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1200)
    at /Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:2867
    at Array.map (<anonymous>)
    at new BucketDeployment (/Users/khaled.ali/development/AWS/Projects/WEB/CDK/ps-serverless-app/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:2848)**

You help is appreciated

Khaled Ali

**Comment by davidtucker** [comment]
The `cdkv2` branch is not finalized yet.  I am working on an update due to a change in bundling.  The supported branches (`p1`, `p2`, `p3`, `p4`, `p5`, and `p6`) all work with the most recent version of the CDK v1. I'll be updating the course for CDK v2 soon.  I'll keep this open until I address the bundling issue.

**Comment by kali70** [comment]
Thank you very much David for your prompt reply. I was working on this for about 2 weeks and could not find any solution on the community.
I will be watching your update when it comes in.
Appreciated,
Khaled Ali
    On Sunday, October 30, 2022 at 06:22:03 p.m. EDT, David Tucker ***@***.***> wrote:  
 
 


The cdkv2 branch is not finalized yet. I am working on an update due to a change in bundling. The supported branches (p1, p2, p3, p4, p5, and p6) all work with the most recent version of the CDK v1. I'll be updating the course for CDK v2 soon. I'll keep this open until I address the bundling issue.

**Comment by elailai94** [comment]
Thanks for the quick update, David! I really appreciate the time and effort you put in to keep the course up-to-date with the CDK updates. I've also been trying to find a workaround for this issue. I'm also following the Building Serverless Applications on AWS path on Pluralsight. I'm learning a lot and love the way that you explain the concepts!

**Comment by askthecloudguy** [comment]
Hi David!
I've been taking your courses in Pluralsight, really love them - appreciate everything you do. I started a project following your serverless course and got stuck here, on deploying the web app. Just like the original poster said - error complains about nothing being produced as an output:
_Error: Bundling did not produce any output. Check that content is written to /asset-output._
Is it something that can be fixed easily? I'd really appreciate any hints. Thank you!
