### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported on "yarn start" command

### ISSUE THREAD

**Issue by Jeewana** [davidtucker/ps-serverless-app#39]
I am getting the following error when running the "yarn start" command on the initial p1 branch. Node version v20.9.0 and yarn version 1.22.22.

Steps:

1. Ran "yarn" command on the root directory. 
2. Changed to webapp directory and ran "yarn start".

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (D:\AWS\ps-serverless-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\AWS\ps-serverless-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\AWS\ps-serverless-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\AWS\ps-serverless-app\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\AWS\ps-serverless-app\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\AWS\ps-serverless-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\AWS\ps-serverless-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\AWS\ps-serverless-app\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
D:\AWS\ps-serverless-app\node_modules\react-scripts\scripts\start.js:19

**Comment by japilarski** [comment]
I have the same issue. 

[EDIT]
I changed the node version to 16 and everything works fine. There's also a closed issue with the same error, which maybe worth checking. :)

**Comment by mmims** [comment]
There is also a workaround of using NODE_OPTIONS="--openssl-legacy-provider" with newer versions of node.
